repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: detect-private-key
    - id: requirements-txt-fixer
    - id: check-added-large-files
      args: [--maxkb=500000]
    - id: check-merge-conflict
    - id: no-commit-to-branch

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=128"

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - --line-length=128
      - id: black-jupyter
